### ISSUE TITLE
SCSS nesting doesn't work

### ISSUE THREAD

**Issue by 1v3n** [gaoxiaoliangz/react-scoped-css#33]
Hi there,

first I want to say thank you for this nice lib. 

In my project nesting classes doesn't work:

webpack config:

```javascript
 {
                    "test": /\.(sc|c|sa)ss$/,
                    "use": [
                        {
                            "loader": "style-loader"
                        },
                        {
                            "loader": "css-loader"
                        },
                        { "loader": "scoped-css-loader" },
                        {
                            "loader": "sass-loader"
                        }
                    ]
                },
```

input:

navbar.scoped.scss:

```css
.navbar {
    .navbar-item{
        color: #fff;
    }
```

navbar.jsx:

```javascript
...
import "./navbar.scoped.scss";
...
<nav ref={this.headerRef} className="navbar">
    <NavbarBrand src={imgUrl} title={title} />
</nav>
```

navbarbrand.jsx:

```javascript
<div className="navbar-brand">
    <NavbarLogo src={src} />
</div>
```

Output: 

HTML:
```html
<nav class="navbar" data-v-a866645d="">
   <div class="navbar-brand">
      <a class="logo navbar-item" href="/" aria-current="page"><img src="static/logo.png"></a>
   </div>
</nav>
```

CSS:
```css
.navbar .navbar-item[data-v-a866645d]  {
    color: #fff;
}
```

I would expect this result:

```css
.navbar[data-v-a866645d] .navbar-item  {
    color: #fff;
}
```
